In [8]:
import numpy as np
A = np.arange(9).reshape((3,3)); A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
np.pad(A, mode='reflect', pad_width=2)

array([[8, 7, 6, 7, 8, 7, 6],
       [5, 4, 3, 4, 5, 4, 3],
       [2, 1, 0, 1, 2, 1, 0],
       [5, 4, 3, 4, 5, 4, 3],
       [8, 7, 6, 7, 8, 7, 6],
       [5, 4, 3, 4, 5, 4, 3],
       [2, 1, 0, 1, 2, 1, 0]])

In [60]:
size = (5, 5)
pad = (size[0]//2, size[1]//2)
shape = A.shape
B = np.zeros((shape[0]+size[0]-1, shape[1]+size[1]-1))
for i in range(shape[0]):
    for j in range(shape[1]):
        B[pad[0]+i][pad[1]+j] = A[i][j]

for i in range(pad[0]):
    for j in range(pad[1]):
        B[i][j] = B[pad[0]*2-i][pad[1]*2-j]

for i in range(pad[0], pad[0]+shape[0]):
    for j in range(pad[1]):
        B[i][j] = B[i][pad[1]*2-j]
        
for i in range(pad[0]+shape[0]-1, pad[0]+shape[0]+pad[0]):
    for j in range(pad[1]):
        B[i][j] = B[(pad[0]+shape[0]-1)*2-i][pad[1]*2-j]
        
for i in range(pad[0]+shape[0]-1, pad[0]+shape[0]+pad[0]):
    for j in range(pad[1]+shape[0]):
        B[i][j] = B[(pad[0]+shape[0]-1)*2-i][j]
        
for i in range(pad[0]+shape[0]-1, pad[0]+shape[0]+pad[0]):
    for j in range(pad[1]+shape[1]-1, pad[1]+shape[1]+pad[1]):
        B[i][j] = B[(pad[0]+shape[0]-1)*2-i][(pad[1]+shape[1]-1)*2-j]

for i in range(pad[0], pad[0]+shape[0]):
    for j in range(pad[1]+shape[1]-1, pad[1]+shape[1]+pad[1]):
        B[i][j] = B[i][(pad[1]+shape[1]-1)*2-j]
        
for i in range(pad[0]):
    for j in range(pad[1]+shape[1]-1, pad[1]+shape[1]+pad[1]):
        B[i][j] = B[pad[0]*2-i][(pad[1]+shape[1]-1)*2-j]
        
for i in range(pad[0]):
    for j in range(pad[0], pad[0]+shape[0]):
        B[i][j] = B[pad[0]*2-i][j]
B

array([[8., 7., 6., 7., 8., 7., 6.],
       [5., 4., 3., 4., 5., 4., 3.],
       [2., 1., 0., 1., 2., 1., 0.],
       [5., 4., 3., 4., 5., 4., 3.],
       [8., 7., 6., 7., 8., 7., 6.],
       [5., 4., 3., 4., 5., 4., 3.],
       [2., 1., 0., 1., 2., 1., 0.]])

In [104]:
size = (5, 5)
pad = (size[0]//2, size[1]//2)
shape = A.shape
L = np.array([[0, pad[0], pad[0]+shape[0]-1, pad[0]+shape[0]+pad[0]-1],
             [0, pad[1], pad[1]+shape[1]-1, pad[1]+shape[1]+pad[1]-1]])

B = np.zeros((shape[0]+size[0]-1, shape[1]+size[1]-1))
for i in range(shape[0]):
    for j in range(shape[1]):
        B[pad[0]+i][pad[1]+j] = A[i][j]

for i in range(3):
    for j in range(3):
        if i is 1 and j is 1:
            continue
        for y in range(L[0,i], L[0,i+1]+1):
            for x in range(L[1,j], L[1,j+1]+1):
                if i is 1:
                    B[y][x] = B[y][L[1,j//2+1]*2-x]
                elif j is 1:
                    B[y][x] = B[L[0,i//2+1]*2-y][x]
                else:
                    B[y][x] = B[L[0,i//2+1]*2-y][L[1,j//2+1]*2-x]
        
(B == np.pad(A, mode='reflect', pad_width=2)).all()

True

In [125]:
import cv2

size=(4,5)
sigmax=2500
sigmay=20

kernelx = cv2.getGaussianKernel(size[0], sigmax)
kernely = cv2.getGaussianKernel(size[1], sigmay)
kernel = np.outer(kernelx, kernely.transpose())
print(kernel)

[[0.04987504 0.05006243 0.05012504 0.05006243 0.04987504]
 [0.04987505 0.05006243 0.05012505 0.05006243 0.04987505]
 [0.04987505 0.05006243 0.05012505 0.05006243 0.04987505]
 [0.04987504 0.05006243 0.05012504 0.05006243 0.04987504]]


In [130]:
def GaussianKernel(n, sigma):
    return [np.exp((-(i**2))/(2*sigma**2))/(2*np.pi()*sigma**2) for i in range(n)]

In [132]:
A = cv2.getGaussianKernel(5, 3); A

array([[0.17820326],
       [0.21052227],
       [0.22254894],
       [0.21052227],
       [0.17820326]])

In [133]:
B = GaussianKernel(5, 3); B

TypeError: 'float' object is not callable